### ISSUE TITLE
AdDir::User.find_by_sid_string ? 

### ISSUE THREAD

**Issue by henrikjohansen** [andibachmann/ad_dir#1]
I sometimes have the need to search for a user by SID string (aka S-1-2-3-444444444-555555555-666666666-7777777) - would that be something you would consider implementing ?

**Comment by andibachmann** [comment]
Hi Henrik

(Hurray, my first issue! ;-) )

This sounds not very demanding. Basically, I have to add a function
`encode_sid(human_readable_sid)' to 'AdDir::Utilities', which does the
contrary of `decode_sid`.

You could then use it like this:

```
AdDir::User.find_by_objectsid(AdDir::Utilities.encode_sid(<human_readable_sid>))
```

Are you patient and will you give me some days?

Regards
Andi

-- 
andi bachmann, bienenstrassse 13, 8004 zürich
tel:+41 43 243 35 64 mobile: +41 76 329 96 13

**Comment by henrikjohansen** [comment]
Hey Andi,

Sure - no problem :)

**Comment by andibachmann** [comment]
Hi @henrikjohansen 

I added a new function `encod_sid` in the `AdDir::Utilities` module (including a little test).

Usage:
```ruby
sid_str = "S-1-5-21-15115519-869956856-4114428504-1105"
user = AdDir::User.find_by_objectsid(AdDir::Utilities.encode_sid(sid_str))
# test the result
user.objectsid_decoded == sid_str
```

Please check it out (i.e. download/pull and build/install the gem) and let me know if it works for you!

Best regards
Andi

**Comment by henrikjohansen** [comment]
Hi @andibachmann 

I believe the correct term is 'Affengeil' ? 

I have run this over a few hundred SID stings and it looks good so far!  This will go into our AD logstash filter and service tens of thousands of lookups per second :)

**Comment by andibachmann** [comment]
@henrikjohansen 

:smiley: 

happy computing!
